:toc: auto
:sectnums:
:toclevels: 4
== 展示の概要
=== クラス展示の概要
本クラス展示「KS魂」では、フジテレビ系で放映されていた「VS嵐」で行われていたゲームを再現しようというものである。本展示では以下の2種類を作成する。

. ローリングコインタワー
. コロコロバイキング

展示場所は教養棟3階 1年4組 HR教室である。

各ゲームの概要は次節以降で述べる。

=== ローリングコインタワーの概要
ローリングコインタワーは、両チーム2名ずつが対角線上にたち、回転する台の上にコインを乗せていくゲームである。 +
各立ち位置に「ゾーン」が設けられ、プレイヤーはタワーが自分のゾーンにある間に必ず3枚コインを乗せなければならない。なお、乗せるコインは3種類あり、それぞれ色・大きさ・ポイントが異なる。 +
展示においては、4人~6人程度が同時にプレイ可能とし、チーム分け等は行わない。 +
高得点者の得点は記録を行う。
展示においては、配点及び大きさ、材質については以下の通りとする。

|===
| コイン直径 | コイン厚み | 配点 | 材質 | 1人あたりの枚数

.3+| 8cm | 6mm | 3pt | 養生用プラダン  (2枚重ね) | 10
| 15mm | 5pt | 発泡スチロール | 8
| 25mm | 10pt | スタイロフォーム1B | 8
|===

=== コロコロバイキングの概要
コロコロバイキングは、3つのゾーンに分割した障害物がある斜面上を転がってくるボールを、落とさないように一番下に位置するゴールに入れるゲームである。 +
ゴールは5分割されており、それぞれ得点が異なる。 +
また、ゴールの得点は毎回シャッフルされる。 +
残り10秒で、10個の小さいボールをほぼ同時に転がってくる。 この時間を「ボーナスタイム」と呼び、ボーナスタイム中は得点はシャッフルされない。 +
ボールは全15球である。それぞれ以下の通りである。

|===
| 球番号 | 大きさ | 得点 | 間隔 |色

| 1~2 .3+| 通常 | x1 .3+| 15s | ブルー  
| 3 | x2 | ゴールデン
| 4~5  .2+| x1 | ブルー
| 6~15  | 小 | 15s+3s | イエロー
|===

== 設計
=== ローリングコインタワー
==== 本体
ローリングコインタワーは、回転台の軽量化がポイントとなる。 +
円盤直径は1.5mで、重量が3kg以下となるように材質を検討した。
回転台はベースに *スタイロフォーム1B 25mm* を用いて軽量化を図る。 +
また、コインを乗せる部分はある程度の硬度が必要だと考えられるため、 *養生用プラダン* を2枚重ねて用いる。 +
ここまでで、ある程度の重量を求めると、今回切り出すスタイロフォームが約0.0442m3でスタイロフォームの重量は約30kg/m3であるため、約1.3kgと計算できる。 +
加えて、プラダンの
また、プラダンは表面に何かを描くのは至難の技であるため、 *A4コピー用紙* を *ボンド木工用 CH38* を用いて張り付ける。 +
なお、その他の部分の接合にも原則 *ボンド木工用 CH38* を用いる。ただし、場合によってはビスなども併用する。

==== 動力部
動力部は、モーターを中心に、数段ギアをかませてトルクの上昇および回転数の低下を図る。 +
ローリングコインタワーの天板の回転数はせいぜい3~4rpm程度であり、今回車航空技術研究部より借用予定のモーター *S13762-130R* はこれを大きく上回る。一方、天板の重量は5kgを超えることが予測されるため、トルクは高いことに越したことはない。ゆえに、このような形式を用いる。 +
また、電子回路中に可変抵抗を組み込み、モーター側可変抵抗で最大出力を、電子回路側可変抵抗で速度の調整を行う。なお、電子回路側可変抵抗にはサーボモーターをつなげ、マイコン *Raspberry Pi Pico W* から制御できるようにする。 +
なお、回路については *LTSpice* 、実際の本体動作は *Autodesk Inventor Professional 2024*, *Autodesk Inventor Nastran 2024* を用いてシミュレーションを行う。 +
動作イメージについては *Blender*,*Natron*,*Olive* および *Maya 2024*,*MotionBuilder 2024*,*Mudbox 2024* を用いて作成する。

== 安全対策
今回は非常に高出力なモーターを扱うため、安全に十分配慮しなければならない。 

=== 共通の対策
以下に、ローリングコインタワー、コロコロバイキング両展示における安全対策を挙げる。