:toc: auto
:sectnums:
:toclevels: 4
== 展示の概要
=== クラス展示の概要
本クラス展示「KS魂」では、フジテレビ系で放映されていた「VS嵐」で行われていたゲームを再現しようというものである。本展示では以下の2種類を作成する。

. ローリングコインタワー
. コロコロバイキング

展示場所は教養棟3階 1年4組 HR教室である。

各ゲームの概要は次節以降で述べる。

=== ローリングコインタワーの概要
ローリングコインタワーは、両チーム2名ずつが対角線上にたち、回転する台の上にコインを乗せていくゲームである。 +
各立ち位置に「ゾーン」が設けられ、プレイヤーはタワーが自分のゾーンにある間に必ず3枚コインを乗せなければならない。なお、乗せるコインは3種類あり、それぞれ色・大きさ・ポイントが異なる。 +
展示においては、4人~6人程度が同時にプレイ可能とし、チーム分け等は行わない。 +
高得点者の得点は記録を行う。
展示においては、配点及び大きさ、材質については以下の通りとする。

|===
| コイン直径 | コイン厚み | 配点 | 材質 | 1人あたりの枚数

.3+| 8cm | 6mm | 3pt | 養生用プラダン  (2枚重ね) | 10
| 15mm | 5pt | 発泡スチロール | 8
| 25mm | 10pt | スタイロフォーム1B | 8
|===

=== コロコロバイキングの概要
コロコロバイキングは、3つのゾーンに分割した障害物がある斜面上を転がってくるボールを、落とさないように一番下に位置するゴールに入れるゲームである。 +
ゴールは5分割されており、それぞれ得点が異なる。 +
また、ゴールの得点は毎回シャッフルされる。 +
残り10秒で、10個の小さいボールをほぼ同時に転がってくる。 この時間を「ボーナスタイム」と呼び、ボーナスタイム中は得点はシャッフルされない。 +
ボールは全15球である。それぞれ以下の通りである。

|===
| 球番号 | 大きさ | 得点 | 間隔 |色

| 1~2 .3+| 通常 | x1 .3+| 15s | ブルー  
| 3 | x2 | ゴールデン
| 4~5  .2+| x1 | ブルー
| 6~15  | 小 | 15s+3s | イエロー
|===

== 設計
=== ローリングコインタワー
==== 本体
ローリングコインタワーは、